package demopackage;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;

@WebServlet("/demoServlet")
public class demoServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");
        
        try {
            String fullName = sanitizeInput(request.getParameter("fullName"));
            String email = sanitizeInput(request.getParameter("email"));
            String phone = sanitizeInput(request.getParameter("phone"));
            String education = sanitizeInput(request.getParameter("education"));
            String skills = sanitizeInput(request.getParameter("skills"));
            String experience = sanitizeInput(request.getParameter("experience"));
            String linkedinProfile = sanitizeInput(request.getParameter("linkedinProfile"));
            
            String resumeContent = generateResumeText(fullName, email, phone, linkedinProfile, education, skills, experience);
            
            response.setContentType("text/plain");
            response.setHeader("Content-Disposition", "attachment; filename=\"" + fullName.replace(" ", "_") + "_Resume.txt\"");
            
            try (PrintWriter out = response.getWriter()) {
                out.write(resumeContent);
            }
        } catch (Exception e) {
            response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Error generating resume");
        }
    }

    private String generateResumeText(String fullName, String email, String phone, String linkedinProfile, String education, String skills, String experience) {
        StringBuilder resume = new StringBuilder();
        resume.append("===============================\n");
        resume.append("           RESUME             \n");
        resume.append("===============================\n");
        resume.append("Name: ").append(fullName).append("\n");
        resume.append("Email: ").append(email).append("\n");
        resume.append("Phone: ").append(phone).append("\n");
        if (!linkedinProfile.isEmpty()) {
            resume.append("LinkedIn: ").append(linkedinProfile).append("\n");
        }
        resume.append("\n");
        
        resume.append("Education:\n");
        resume.append(education).append("\n\n");
        
        resume.append("Skills:\n");
        for (String skill : skills.split(",")) {
            resume.append("- ").append(skill.trim()).append("\n");
        }
        resume.append("\n");
        
        resume.append("Work Experience:\n");
        resume.append(experience).append("\n");
        
        resume.append("===============================\n");
        resume.append("Generated by Resume Generator\n");
        
        return resume.toString();
    }

    private String sanitizeInput(String input) {
        return input == null ? "" : input.replaceAll("<", "&lt;").replaceAll(">", "&gt;").trim();
    }
}